# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  test:
    cmds:
      - vitest run src
  test:dev:
    cmds:
      - vitest src

  check:
    deps:
      - histoire:build
    cmds:
      - { task: test }

  histoire:build:
    sources:
      - src/lib/components/**
    generates:
      - .histoire/screenshots/**
    cmds:
      - histoire build

  integrate:
    deps: [check]
    cmds:
      - git is-clean
      - git checkout main
      - git weld -

  release:
    cmds:
      - standard-version -a
  changelog:
    sources: [CHANGELOG.md]
    generates: [src/lib/components/Changelog.svelte]
    cmds:
      - pnpx showdown makehtml -i CHANGELOG.md -o src/lib/components/Changelog.svelte
      - git add src/lib/components/Changelog.svelte

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
