# https://taskfile.dev

version: "3"

vars:
  PARENT_BRANCH: main

tasks:
  test:
    cmds:
      - vitest run src
  test:dev:
    cmds:
      - vitest src

  test:update:
    deps:
      - histoire:build
    cmds:
      - vitest run -u src 

  check:
    deps:
      - histoire:build
    cmds:
      - { task: test }

  histoire:build:
    sources:
      - src/lib/components/**
    generates:
      - .histoire/screenshots/**
    cmds:
      - histoire build

  integrate:
    deps: [check]
    cmds:
      - git is-clean
      # did we had tests?
      - git diff-ls  {{.PARENT_BRANCH}} | grep test
      - git checkout {{.PARENT_BRANCH}}
      - git weld -

  release:
    cmds:
      - standard-version -a
  changelog:
    sources: [CHANGELOG.md]
    generates: [src/lib/components/Changelog.svelte]
    cmds:
      - pnpx showdown makehtml -i CHANGELOG.md -o src/lib/components/Changelog.svelte
      - git add src/lib/components/Changelog.svelte

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
