# https://taskfile.dev

version: "3"

vars:
  PARENT_BRANCH: main

tasks:
  test:
    cmds:
      - vitest run src
  test:dev:
    cmds:
      - vitest src

  test:update:
    deps:
      - histoire:build
    cmds:
      - vitest run -u src

  check:
    # deps:
    #   - histoire:build
    cmds:
      - { task: test }

  histoire:build:
    sources:
      - src/lib/components/**
      - src/routes/**
    generates:
      - .histoire/screenshots/**
    cmds:
      - histoire build

  changelog:
    sources: [CHANGELOG.yml]
    generates: [CHANGELOG.md]
    cmds:
      - changelord print --no-next > CHANGELOG.md
      - changelord print --no-next > 'src/routes/(about)/about/changelog/changelog.svx'

  build:
    deps: [changelog]
    cmds:
      - vite build

  integrate:
    deps: [check]
    preconditions:
      - sh: git is-clean
        msg: checkout not clean
      - sh: git diff-ls  {{.PARENT_BRANCH}} | grep test
        msg: no test was added
      - sh: git diff-ls  {{.PARENT_BRANCH}} | grep CHANGELOG.yml
        msg: no changelog entry detected
    cmds:
      - git checkout {{.PARENT_BRANCH}}
      - git weld -

  publish:
    cmds:
      - { task: build }
      # tag
      - { task: sync }

  sync:
    cmds:
      - rsync -av build/ 192.168.0.100:/home/docks

  open: firefox https://docks.babyl.ca
