# https://taskfile.dev

version: "3"

vars:
  PARENT_BRANCH: main

tasks:
  test:
    cmds:
      - vitest run src
  test:dev:
    cmds:
      - vitest src

  test:update:
    deps:
      - histoire:build
    cmds:
      - vitest run -u src

  check:
    # deps:
    #   - histoire:build
    cmds:
      - { task: test }

  histoire:build:
    sources:
      - src/lib/components/**
      - src/routes/**
    generates:
      - .histoire/screenshots/**
    cmds:
      - histoire build

  build:
    cmds:
      - changelord print --no-next > src/routes/\(about\)/about/changelog/changelog.svx
      - vite build

  integrate:
    deps: [check]
    preconditions:
      - sh: git is-clean
        msg: checkout not clean
      - sh: git diff-ls  {{.PARENT_BRANCH}} | grep test
        msg: no test was added
      - sh: git diff-ls  {{.PARENT_BRANCH}} | grep CHANGELOG.yml
        msg: no changelog entry detected
    cmds:
      - git checkout {{.PARENT_BRANCH}}
      - git weld -

  sync:
    cmds:
      - rsync -av build/ 192.168.0.100:/home/docks

  open: firefox https://docks.babyl.ca

  release:
    cmds:
      - standard-version -a

  changelog:
    sources: [CHANGELOG.md]
    generates: [src/lib/components/Changelog.svelte]
    cmds:
      - pnpx showdown makehtml -i CHANGELOG.md -o src/lib/components/Changelog.svelte
      - git add src/lib/components/Changelog.svelte
